Repository RossSihovsk/LifeOS, pull requests merged in 2024-02, with the labels that each got.

#11 [Task 8,9,10] Create project structure
  .fleet/receipt.json
  composeApp/src/androidMain/kotlin/Platform.android.kt
  composeApp/src/androidMain/kotlin/com/project/LifeOsApplication.kt
  composeApp/src/androidMain/kotlin/com/project/lifeos/MainActivity.kt
  composeApp/src/androidMain/kotlin/com/project/lifeos/ui/HomeScreen.android.kt
  composeApp/src/commonMain/kotlin/App.kt
  composeApp/src/commonMain/kotlin/Greeting.kt
  composeApp/src/commonMain/kotlin/Platform.kt
  composeApp/src/commonMain/kotlin/com/project/lifeos/App.kt
  composeApp/src/commonMain/kotlin/com/project/lifeos/data/ActivityIcon.kt
  composeApp/src/commonMain/kotlin/com/project/lifeos/data/Goal.kt
  composeApp/src/commonMain/kotlin/com/project/lifeos/data/Task.kt
  composeApp/src/commonMain/kotlin/com/project/lifeos/interactor/TestInteractor.kt
  composeApp/src/commonMain/kotlin/com/project/lifeos/repository/TestRepository.kt
  composeApp/src/commonMain/kotlin/com/project/lifeos/ui/HomeScreen.kt
  composeApp/src/commonMain/kotlin/com/project/lifeos/viewmodel/HomeViewModel.kt
  composeApp/src/desktopMain/kotlin/Platform.jvm.kt
  composeApp/src/desktopMain/kotlin/com/project/lifeos/ui/HomeScreen.desktop.kt
  composeApp/src/desktopMain/kotlin/main.kt
  gradle/libs.versions.toml
Labels: ready to review, testing done

#14 [Task 13] Added Navigation library Voyager
  composeApp/build.gradle.kts
  composeApp/src/androidMain/kotlin/com/project/lifeos/ui/HomeScreen.android.kt
  composeApp/src/androidMain/kotlin/com/project/lifeos/ui/screen/AddTaskScreen.android.kt
  composeApp/src/androidMain/kotlin/com/project/lifeos/ui/screen/HomeScreen.android.kt
  composeApp/src/commonMain/kotlin/com/project/lifeos/App.kt
  composeApp/src/commonMain/kotlin/com/project/lifeos/ui/HomeScreen.kt
  composeApp/src/commonMain/kotlin/com/project/lifeos/ui/bottomNavigation/BottomBar.kt
  composeApp/src/commonMain/kotlin/com/project/lifeos/ui/bottomNavigation/BottomNavigationItem.kt
  composeApp/src/commonMain/kotlin/com/project/lifeos/ui/screen/AddTaskScreen.kt
  composeApp/src/commonMain/kotlin/com/project/lifeos/ui/screen/HomeScreen.kt
  composeApp/src/desktopMain/kotlin/com/project/lifeos/ui/HomeScreen.desktop.kt
  composeApp/src/desktopMain/kotlin/com/project/lifeos/ui/screen/AddTaskScreen.desktop.kt
  composeApp/src/desktopMain/kotlin/com/project/lifeos/ui/screen/HomeScreen.desktop.kt
  gradle/libs.versions.toml
Labels: ready to review, task

#21 Added Kermit Library
  composeApp/build.gradle.kts
  composeApp/src/androidMain/kotlin/com/project/lifeos/MainActivity.kt
  composeApp/src/commonMain/kotlin/com/project/lifeos/App.kt
  composeApp/src/desktopMain/kotlin/main.kt
  gradle/libs.versions.toml
Labels: ready to review
